name = "cloudflare-gql-api"
main = "worker/script.js"
compatibility_date = "2022-06-16"

# node_compat = true

[build]
command = "npm run build" # or "yarn build"

[dev]
local_protocol="http"
upstream_protocol="https"
port = 8080
