`
"""
This file was generated by cf-graphql-schema-generator which was forked from
https://github.com/prisma-korea/graphql-schema-generator.

Do not make changes to this file directly.
Read more about in https://github.com/edwinbrowwn/cf-graphql-schema-generator.
"""
`
export const schema = ` type Query {
  todo(id: ID!): todo
  todos: [todo!]!
}

input todoCreateInput {
  task: String!
  completed: Boolean!
  created_at: DateTime!
  updated_at: DateTime
}

input todoUpdateInput {
  task: String
  completed: Boolean
  created_at: DateTime
  updated_at: DateTime
}

type Mutation {
  createtodo(todo: todoCreateInput!): todo
  updatetodo(todo: todoUpdateInput!): todo
  deletetodo(id: ID!): todo
}

scalar DateTime

type todo {
  id: ID!
  task: String!
  completed: Boolean!
  created_at: DateTime!
  updated_at: DateTime
}` 
export default schema;