`
"""
This file was generated by cf-graphql-schema-generator which was forked from
https://github.com/prisma-korea/graphql-schema-generator.

Do not make changes to this file directly.
Read more about in https://github.com/edwinbrowwn/cf-graphql-schema-generator.
"""
`
export const schema = ` type Query {
  pokemon(public_id: ID!): pokemon
  pokemons: [pokemon!]!
}

input pokemonCreateInput {
  name: String!
  height: Int!
  weight: Int!
}

input pokemonUpdateInput {
  name: String
  height: Int
  weight: Int
}

type Mutation {
  createpokemon(pokemon: pokemonCreateInput!): pokemon
  updatepokemon(pokemon: pokemonUpdateInput!): pokemon
  deletepokemon(public_id: ID!): pokemon
}

type pokemon {
  public_id: ID!
  name: String!
  height: Int!
  weight: Int!
}` 
export default schema;